name: Run interpolation.py on Release

on:
  release:
    types:
      - published

jobs:
  run-interpolation:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the interpolation.py script
      - name: Run interpolation.py
        run: python interpolation.py

      # Upload the generated file to the release
      - name: Upload PNG to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Temp_natural_neighbor.png
          asset_name: result.png
          asset_content_type: image/png
